name: "issue-auto-lock"
description: "Automatically manage issues based on stargazer status."
inputs:
  gh_token:
    description: "GitHub token for authentication"
    required: true
  gh_repo:
    description: "Repository name to manage issues"
    required: true
  issue_labels:
    description: "Comma-separated list of labels to apply to the issue"
    required: false
    default: "haven't given me a star"
  issue_close_comment:
    description: "Comment to post when closing the issue"
    required: false
    default: "Thank you for opening this issue. I noticed that you haven not given me a star yet, so I will close this issue. Please give me a star first and wait for it to be unlocked. Thank you for your understanding."
  issue_reopen_comment:
    description: "Comment to post when reopening the issue"
    required: false
    default: "Thank you for giving me a star. I have unlocked this issue. If you have any questions, please feel free to ask. Thank you for your support."
  white_list:
    description: "Comma-separated list of users who can open issues without giving a star"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: "devhaozi/issue-auto-lock"
        token: ${{ inputs.gh_token }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    # - name: List files
    #   run: ls -la
    #   shell: bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash
    - name: Run script
      run: python issue_auto_lock.py
      env:
        GH_REPO: ${{ inputs.gh_repo }}
        GH_TOKEN: ${{ inputs.gh_token }}
        ISSUE_LABELS: ${{ inputs.issue_labels }}
        ISSUE_CLOSE_COMMENT: ${{ inputs.issue_close_comment }}
        ISSUE_REOPEN_COMMENT: ${{ inputs.issue_reopen_comment }}
        WIHTE_LIST: ${{ inputs.white_list }}
      shell: bash
branding:
  icon: "zap"
  color: "red"
