name: "auto lock baipiao"
description: "Automatically manage issues based on stargazer status."
inputs:
  gh_token:
    description: "GitHub token for authentication"
    required: true
  gh_repo:
    description: "Repository name to manage issues"
    required: true
  issue_labels:
    description: "Comma-separated list of labels to apply to the issue"
    required: true
    default: "need-review"
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.gh_repo }}
        token: ${{ inputs.gh_token }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: List files
      run: ls -la
      shell: bash
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash

    - name: Run script
      run: python issues_baipiao_checker.py
      env:
        GH_REPO: ${{ inputs.gh_repo }}
        GH_TOKEN: ${{ inputs.gh_token }}
        ISSUE_LABELS: ${{ inputs.issue_labels }}
      shell: bash

branding:
  icon: "zap"
  color: "red"
