name: 'auto lock baipiao'
description: 'Automatically manage issues based on stargazer status.'
inputs:
  gh_token:
    description: 'GitHub token for authentication'
    required: true
  gh_repo:
    description: 'Repository name to manage issues'
    required: true
  issue_labels:
    description: 'Comma-separated list of labels to apply to the issue'
    required: true
    default: 'need-review'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py
      env:
        GH_REPO: ${{ inputs.gh_repo }}
        GH_TOKEN: ${{ inputs.gh_token }}
        ISSUE_LABELS: ${{ inputs.issue_labels }}