name: Issue Management Automation

on:
  schedule:
    - cron: "0 18 * * *"   #"0 18 * * *"  "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  issues:
    types: [opened]

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Lock Baipiao
        uses: 14790897/auto-lock-baipiao@0.1.1
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          gh_repo: ${{ secrets.GH_REPO }}
          issue_labels: ${{ secrets.ISSUE_LABELS }}
