name: Auto Lock Baipiao
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  issues:
    types: [opened]
permissions:
  issues: write
  contents: read
jobs:
  issue-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Set GH_REPO
        run: echo "GH_REPO=${{ github.repository }}" >> $GITHUB_ENV
      - name: Auto Lock Baipiao
        uses: 14790897/auto-lock-baipiao@v0.1.7
        with:
          gh_repo: ${{ env.GH_REPO }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: "haven't given me a star ⭐"
          issue_close_comment: "Thank you for opening this issue. I noticed that you haven not given me a star yet, so I will close this issue. Please give me a star first and wait for it to be unlocked. Thank you for your understanding."
          issue_reopen_comment: "Thank you for giving me a star. I have unlocked this issue. If you have any questions, please feel free to ask. Thank you for your support."
          white_list: "1"
