name: Issue Management Action

on:
  # schedule:
  #   - cron: "0 9-17 * * *" #"0 18 * * *"  "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  manage-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Set GH_REPO
        run: echo "GH_REPO=${{ secrets.GH_REPO || github.repository }}" >> $GITHUB_ENV
      - name: Auto Lock Baipiao
        uses: 14790897/auto-lock-baipiao@v0.1.7
        with:
          gh_repo: ${{ secrets.GH_REPO || github.repository }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          issue_labels: ${{ secrets.ISSUE_LABELS }}
